DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS participation_requests CASCADE;
DROP TABLE IF EXISTS event_user CASCADE;
DROP TABLE IF EXISTS event_compilation CASCADE;


CREATE TABLE if not exists "users"
(
    "id"      bigint primary key generated by default as identity,
    "email"   varchar(255) UNIQUE,
    "name"    varchar(255),
    "created" timestamp without time zone
);

CREATE TABLE if not exists "category"
(
    "id"          bigint primary key generated by default as identity,
    "name"        varchar(100) UNIQUE,
    "created"     timestamp without time zone
);

CREATE TABLE if not exists "events"
(
    "id"                 bigint primary key generated by default as identity,
    "title"              varchar(150),
    "annotation"         varchar(2000),
    "description"        varchar(7000),
    "category_id"        bigint references category (id),
    "initiator_id"       bigint references users (id),
    "participant_limit"  int,
    "confirmed_requests" int,
    "lat"                float,
    "lon"                float,
    "paid"               boolean,
    "request_moderation" boolean ,
    "status"             varchar(255),
    "published_on"       timestamp without time zone,
    "event_date"         timestamp without time zone,
    "created"            timestamp without time zone
);

CREATE TABLE if not exists "compilations"
(
    "id"      bigint primary key generated by default as identity,
    "title"   varchar(100),
    "pinned"  boolean,
    "created" timestamp without time zone
);


CREATE TABLE if not exists "participation_requests"
(
    "id"           bigint primary key generated by default as identity,
    "event_id"     bigint references events (id),
    "requestor_id" bigint references users (id),
    "status"       varchar(255),
    "created"      timestamp without time zone
);

CREATE TABLE if not exists "event_user"
(
    "id"           bigint primary key generated by default as identity,
    "event_id"     bigint references events (id),
    "requestor_id" bigint references users (id)
);

CREATE TABLE if not exists "event_compilation"
(
    "id"             bigint primary key generated by default as identity,
    "event_id"       bigint references events (id),
    "compilation_id" bigint references compilations (id)
);
