DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        VARCHAR(100)                            NOT NULL,
    uri        VARCHAR(510)                            NOT NULL,
    ip         VARCHAR(100)                            NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);
