INSERT INTO statuses (status)
VALUES ('PENDING')
ON CONFLICT DO NOTHING;

INSERT INTO statuses (status)
VALUES ('PUBLISHED')
ON CONFLICT DO NOTHING;

INSERT INTO statuses (status)
VALUES ('CANCELED')
ON CONFLICT DO NOTHING;

INSERT INTO statuses (status)
VALUES ('CONFIRMED')
ON CONFLICT DO NOTHING;

INSERT INTO statuses (status)
VALUES ('REJECTED')
ON CONFLICT DO NOTHING;