DROP TABLE IF EXISTS stat CASCADE;

create table if not exists "stat"
(
    "id"        bigint primary key generated by default as identity,
    "app"       varchar(255),
    "uri"       varchar(255),
    "ip"        varchar(255),
    "timestamp" timestamp without time zone
);