DROP TABLE IF EXISTS endpoints;

create table endpoints(
    id BIGINT generated by default as identity not null ,
    app VARCHAR(255) not null ,
    uri VARCHAR(255) not null,
    ip varchar(255) not null ,
    stamp TIMESTAMP
);