-- DROP TABLE IF EXISTS hits CASCADE ;

CREATE TABLE IF NOT EXISTS hits
(
    id        bigint generated by default as identity primary key,
    app       varchar(100),
    uri       varchar(100),
    ip        varchar(100),
    timestamp timestamp without time zone
);