drop table if exists stats;

create table stats
(
    id       integer generated by default as identity,
    app      varchar(255) not null,
    uri      varchar(500) not null,
    ip       varchar(30)  not null,
    hit_date timestamp    not null
);