CREATE TABLE IF NOT EXISTS hits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        VARCHAR(250)                            NOT NULL,
    uri        VARCHAR(250)                            NOT NULL,
    ip         VARCHAR(25)                             NOT NULL,
    time_stamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_hit PRIMARY KEY (id)
);